# doc-warnings: no
# test-warnings: yes
# strictness: medium
# autodetect: yes
# max-line-length: 120
# requirements:
#     - requirements.txt
#     - requirements-pipes.txt
# ignore-paths:
#     - docs
#     - tools/build
# python-targets:
#     - 2
#     - 3

dodgy:
  run: false
mccabe:
  run: false #mccabe is seemingly problematic
pyflakes:
  run: yes
pep8:
  run: yes
pylint:
  run: false
pep257:
  run: false # problematic for __all__ statements
profile-validator:
  run: false
# optional:
frosted:
  run: false
vulture:
  run: false
pyroma:
  run: false