doc-warnings: no
test-warnings: yes
strictness: medium
autodetect: yes
max-line-length: 120
requirements:
    - requirements.txt
    - requirements-pipes.txt
ignore-paths:
    - docs
    - tools/build
python-targets:
    - 2
    - 3
pep257:
  run: false