doc-warnings: no # "no" disables pep257, which has issues parsing complex __all__ statements
test-warnings: yes
strictness: medium
max-line-length: 120
requirements:
    - requirements.txt
    - requirements-pipes.txt
ignore-paths:
    - docs
python-targets:
    - 2
    - 3
