dodgy:
  run: false
mccabe:
  run: false 
pyflakes:
  run: yes
pep8:
  run: yes
pylint:
  run: yes
pep257:
  run: false 
profile-validator:
  run: false




frosted:
  run: false
vulture:
  run: false
pyroma:
  run: false