dist: trusty
os: linux

git:
  depth: 150

env:
  global:
  - CACHE_DIR="$HOME/misc_cache"
  - MINICONDA_DIR="$HOME/miniconda"
  - PIP_DIR="$HOME/virtualenv"
  - GATK_PATH="$CACHE_DIR"
  - PYTHONIOENCODING=UTF8
  - PYTEST_ADDOPTS="-rsxX -x -n 2 --durations=25 --fixture-durations=10 --junit-xml=pytest.xml --cov-report= --cov broad_utils --cov illumina --cov assembly --cov interhost --cov intrahost --cov metagenomics --cov ncbi --cov read_utils --cov kmer_utils --cov reports --cov taxon_filter --cov tools --cov util --cov file_utils --parts-tot=2"
  
  - DOCKER_REGISTRY="quay.io"
  - DOCKER_REPO_PROD="quay.io/broadinstitute/viral-ngs"
  - DOCKER_REPO_DEV="quay.io/broadinstitute/viral-ngs-dev"
  
  - DOCKER_REGISTRY_MIRROR="docker.io"
  - DOCKER_REPO_PROD_MIRROR="broadinstitute/viral-ngs"
  
  - BOTO_CONFIG=/dev/null # bogus value to override config on travis
  - _JAVA_OPTIONS="-Xmx3g" # overrides jvm opts set elsewhere; see: https://stackoverflow.com/questions/28327620/difference-between-java-options-java-tool-options-and-java-opts

cache:
  directories:
    - $HOME/misc_cache
    - $HOME/miniconda
  timeout: 1000

#stages:
#  - build
#  - test

jobs:
  fast_finish: true
  include:

    - language: python
      python: 3.6
      #stage: test
      sudo: required
      env:
        - TRAVIS_JOB=test_py36_part2
        # DX_API_TOKEN (for DNAnexus builds)
        - secure: "BnUw6ceEClSBFJjZgCy6GebD1ENxaHp3En05maWExdx0xyCb+T09XM1BrsCpPOv25npVUt8Q/YB6YpAiSGMT+RUwdiGj4OtaJb+I3HY/2fT1P7eCIEVITQhtGy5e/vFnavSk0eKzCV09z94c1kqjG3JnTocpPUa1W3JBxVr96vs="
        - DX_PROJECT=project-F8PQ6380xf5bK0Qk0YPjB17P
        - VIRAL_NGS_DX_TESTS=1
      before_install: travis/before_install.sh
      install:
        - source travis/install-conda.sh
        - travis/install-gatk.sh
        - travis/install-tools.sh
        - source travis/activate-conda.sh
      script:
        - travis/tests-pytest.sh
      after_success:
        - coveralls
      before_cache:
        - conda clean --all --yes
