dist: trusty
os: linux

git:
  depth: 150

env:
  global:
  - CACHE_DIR="$HOME/misc_cache"
  - MINICONDA_DIR="$HOME/miniconda"
  - PIP_DIR="$HOME/virtualenv"
  - GATK_PATH="$CACHE_DIR/GenomeAnalysisTK-3.6"
  - PYTHONIOENCODING=UTF8
  
  - DOCKER_REGISTRY="quay.io"
  - DOCKER_REPO_PROD="quay.io/broadinstitute/viral-ngs"
  - DOCKER_REPO_DEV="quay.io/broadinstitute/viral-ngs-dev"
  
  - DOCKER_REGISTRY_MIRROR="docker.io"
  - DOCKER_REPO_PROD_MIRROR="broadinstitute/viral-ngs"
  
  - BOTO_CONFIG=/dev/null # bogus value to override config on travis
  - _JAVA_OPTIONS="-Xmx3g" # overrides jvm opts set elsewhere; see: https://stackoverflow.com/questions/28327620/difference-between-java-options-java-tool-options-and-java-opts

cache:
  directories:
    - $HOME/misc_cache
    - $HOME/miniconda
  timeout: 480

#stages:
#  - build
#  - test

jobs:
  fast_finish: true
  include:

###################################################
# Building docker container for viral-ngs;
# compiling WDL workflows to DNAnexus;
# testing WDL workflows on DNANexus and locally.
###################################################
    - language: java
      jdk: oraclejdk8
      sudo: required
      addons:
        apt:
          packages:
          - docker-ce
      env:
        - TRAVIS_JOB=docker_wdl
        # DOCKER_USER (for Quay.io)
        - secure: R5NXHDxFzoogYf2qlk9O0G7xWJ8JCD/y4XA06Vq902udfFWy+O4h7ftGTHjwQdyufrZFUZEhXNbXPX/xMTn73u/puKr5m4lm8Bg1aVDUumyDmyQqxwQsnSF0fOld+FEG5j1FnT7Mf5V+F96KUH6/YXjndAjYxGSEUsJQ+C413YY=
        # DOCKER_PASS (for Quay.io)
        - secure: ZrX/Hq6T3X1Nw83+wjoAia9h6g00o8hV/dJAONnWYflpeSc16AKs8d4bBKPxE+rW+8I8JzoUWpdgN9Zq87+Vd3la8V4S1NCw7iZFYshzOZIbXtJZIC18NqsWDL5Kg0Ud08Y5GlI14Rjyc/zWmn5LmAHbZLk9EudtrcUmUmce1Ek=
        ## DOCKER_USER_MIRROR (for DockerHub)
        - secure: NErgcpFHK3Q51idZumScyRlr6PJjuFirHXlJJSPFhtKBh1Gg+z2Z3DLoFCOTibIyJSVo38T2eA53daM3VmPWb3kd4brrLjjoH7a3i/838IJjIDLpFULAc3uzP7PGckEiXb8gB1lQB/IaeDiWWUL2SbzMOdLABpANpR1AYmF00VI=
        ## DOCKER_PASS_MIRROR (for DockerHub)
        - secure: PGfcYRtbZJSa09ZPGguBWyZAiUBnRkQRgowg3qasK4hT2vlhXOqgSmQNwRHHbUZA7d/s11u6Q4732L1+JnelnFc9yDTVDguawvM9ENrDYjDe4bZPMqbxsUWOCSPSd8JSjvcOtg+BLGhzmwxYFIRl5jOoS8Wkvos1fRpKbYNRY20=
        # DX_API_TOKEN (for DNAnexus builds)
        - secure: RENKuendRiAmWxn+lgGF+XXPUHzfRDHGUaP4uR5mpnKOqGKVZX3uadFv/w1POuyxIR7QEt0EcgtbjJYsvEioyQRwsYQe9f1ekQU1k6+cyPS/eDqvwciXA2M+yqjNdAafQu4drN+aNV7qC8ZEU0MZXk3IaItB4g8z5ZfxfM54+m0=
        - DX_PROJECT=project-F8PQ6380xf5bK0Qk0YPjB17P
        # $BUNDLE_SECRET (for testing GATK on Cromwell-local and DNAnexus)
        - secure: KX7DwKRD85S7NgspxevgbulTtV+jHQIiM6NBus2/Ur/P0RMdpt0EQQ2wDq79qGN70bvvkw901N7EjSYd+GWCAM7StXtaxnLRrrZ3XI1gX7KMk8E3QzPf0zualLDs7cuQmL6l6WiElUAEqumLc7WGpLZZLdSPzNqFSg+CBKCmTI8=
        # $VIRAL_NGS_METADATA_PATH (for testing metadata logging to s3)
        - secure: "YsQou7q6EqbfjuD6dpaKoYJBMZC2ZSHBsSN4C27ZmvR4sLFRZFpxYsr2YGQpruuvDGZMyL8gBBEfYr7E1TtnupA2WwCPnlJzHkPpy8sTaJ1az2GcjNvHwGDKybD4ZKSMREALHMUIMCa30ae3EPHRgDxCzEdfpoIF9zezeHgbxds="        
      install:
        #- travis/upgrade-docker.sh
        - travis/install-wdl.sh
        - travis/install-gatk.sh
      script:
        - set -e
        # pull old docker image
        - if [ -f "$CACHE_DIR/old-docker-tag.txt" ]; then OLD_DOCKER_TAG=$(cat $CACHE_DIR/old-docker-tag.txt); else OLD_DOCKER_TAG=$DOCKER_REPO_PROD; fi; echo "old docker tag = $OLD_DOCKER_TAG"
        - if docker pull $OLD_DOCKER_TAG; then _CACHE_FROM="--cache-from $OLD_DOCKER_TAG"; else _CACHE_FROM=""; fi
        # build new docker image
        - docker build -t local/viral-ngs:build $_CACHE_FROM .;
        # deploy docker image
        - travis/deploy-docker.sh
        # version and validate WDL code
        - travis/version-wdl-runtimes.sh
        - travis/validate-wdl.sh
        # build DNAnexus pipelines and launch a few test executions
        - travis/build-dx.sh
        - travis/tests-dx.sh
        #- if [ "$TRAVIS_BRANCH" = "master" ]; then travis/tests-dx.sh; fi
        # test Cromwell local execution engine
        - travis/tests-cromwell.sh
      before_cache:
        - travis/list-docker-tags.sh | tail -1 > $CACHE_DIR/old-docker-tag.txt

###########################
# Building documentation
##########################
        
    # - language: python
    #   sudo: false
    #   #stage: build
    #   env: TRAVIS_JOB=build_docs
    #   install: travis/install-pip-docs.sh
    #   script: travis/build-docs.sh

############################
# Building a conda package
############################

    # - language: python
    #   python: 3.6
    #   sudo: required
    #   #stage: test
    #   env:
    #     - TRAVIS_JOB=build_conda
    #     # $ANACONDA_TOKEN for uploading builds to anaconda.org ("broad-viral" channel)
    #     - secure: SLPB86BpMIiNncMioxVk9cLrqaSNt8F1QDtxkrdLq9j7wXzFqGa7cipG6UJ6Om7GvoF49DpACfGPTA4ycr+T4cH3pWXpBHrBhV8TyKJb23cOmg5+7zqJQTzuwNqKOT7t9rnBkf1uzVXBcgqKaD6XW/nEvNFK00I0cvjlCp8vgxE=
    #     # $BUNDLE_SECRET (for testing GATK)
    #     - secure: KX7DwKRD85S7NgspxevgbulTtV+jHQIiM6NBus2/Ur/P0RMdpt0EQQ2wDq79qGN70bvvkw901N7EjSYd+GWCAM7StXtaxnLRrrZ3XI1gX7KMk8E3QzPf0zualLDs7cuQmL6l6WiElUAEqumLc7WGpLZZLdSPzNqFSg+CBKCmTI8=
    #   install:
    #     - source travis/install-conda.sh
    #     - travis/install-conda-build.sh
    #   script:
    #     - travis/build-conda.sh
    #   before_cache:
    #     - conda clean --all --yes

################################
# Running the test suite (py27)
################################

#     - language: python
#       python: 2.7
#       #stage: test
#       sudo: required
#       env:
#         - TRAVIS_JOB=test_py27
#         - VIRAL_NGS_METADATA_VALUE_travis_job=test_py27
#         - PYTEST_ADDOPTS="-rsxX -n 2 --durations=25 --fixture-durations=10 --junit-xml=pytest.xml --cov-report= --cov broad_utils --cov illumina --cov assembly --cov interhost --cov intrahost --cov metagenomics --cov ncbi --cov read_utils --cov reports --cov taxon_filter --cov tools --cov util"
#         # $BUNDLE_SECRET (for testing GATK)
#         - secure: KX7DwKRD85S7NgspxevgbulTtV+jHQIiM6NBus2/Ur/P0RMdpt0EQQ2wDq79qGN70bvvkw901N7EjSYd+GWCAM7StXtaxnLRrrZ3XI1gX7KMk8E3QzPf0zualLDs7cuQmL6l6WiElUAEqumLc7WGpLZZLdSPzNqFSg+CBKCmTI8=
#         # $VIRAL_NGS_METADATA_PATH (for testing metadata logging to s3)
#         - secure: Cd7ch+n8OT0KtA9MhTz1pfXbThJbIQ74oxbSkLGXZKwS52LWwaCH6dtBBbSqXUp9cnxsZhYkxjCmRNgAmBuUh0CpUtgN71YNegYPtLRO1seihqVc3TQC+cgwQxd1hNrsFfAvXwlReLMJgKydGDago0oe5/7df5P+YFAi3w/MKCE=
#       before_install: travis/before_install.sh
#       install:
#         - source travis/install-conda.sh
#         - travis/install-gatk.sh
#         - travis/install-tools.sh
#         - source travis/activate-conda.sh
#       script:
#         - travis/tests-unit.sh
#         - travis/tests-long.sh
#       before_cache:
#         - conda clean --all --yes

#     - language: python
#       python: 3.6
#       #stage: test
#       sudo: required
#       env:
#         - TRAVIS_JOB=test_py36
#         - VIRAL_NGS_METADATA_VALUE_travis_job=test_py36
#         - PYTEST_ADDOPTS="-rsxX -n 2 --durations=25 --fixture-durations=10 --junit-xml=pytest.xml --cov-report= --cov broad_utils --cov illumina --cov assembly --cov interhost --cov intrahost --cov metagenomics --cov ncbi --cov read_utils --cov reports --cov taxon_filter --cov tools --cov util"
#         # $BUNDLE_SECRET (for testing GATK)
#         - secure: KX7DwKRD85S7NgspxevgbulTtV+jHQIiM6NBus2/Ur/P0RMdpt0EQQ2wDq79qGN70bvvkw901N7EjSYd+GWCAM7StXtaxnLRrrZ3XI1gX7KMk8E3QzPf0zualLDs7cuQmL6l6WiElUAEqumLc7WGpLZZLdSPzNqFSg+CBKCmTI8=
#         # $VIRAL_NGS_METADATA_PATH (for testing metadata logging to s3)
#         - secure: Cd7ch+n8OT0KtA9MhTz1pfXbThJbIQ74oxbSkLGXZKwS52LWwaCH6dtBBbSqXUp9cnxsZhYkxjCmRNgAmBuUh0CpUtgN71YNegYPtLRO1seihqVc3TQC+cgwQxd1hNrsFfAvXwlReLMJgKydGDago0oe5/7df5P+YFAi3w/MKCE=
#       before_install: travis/before_install.sh
#       install:
#         - source travis/install-conda.sh
#         - travis/install-gatk.sh
#         - travis/install-tools.sh
#         - source travis/activate-conda.sh
#       script:
#         - travis/tests-long.sh
#         - travis/tests-unit.sh
#       after_success:
#         - coveralls
#       before_cache:
#         - conda clean --all --yes

####################################
# Running the test suite (snakemake)
####################################

#     - language: python
#       python: 3.6
#       #stage: test
#       sudo: required
#       env:
#         - TRAVIS_JOB=test_snakemake
#         - VIRAL_NGS_METADATA_VALUE_travis_job=test_snakemake
#         - PYTEST_ADDOPTS="-rsxX -n 2 --durations=25 --fixture-durations=10 --junit-xml=pytest.xml --cov-report= --cov broad_utils --cov illumina --cov assembly --cov interhost --cov intrahost --cov metagenomics --cov ncbi --cov read_utils --cov reports --cov taxon_filter --cov tools --cov util"
#         # $BUNDLE_SECRET (for testing GATK)
#         - secure: KX7DwKRD85S7NgspxevgbulTtV+jHQIiM6NBus2/Ur/P0RMdpt0EQQ2wDq79qGN70bvvkw901N7EjSYd+GWCAM7StXtaxnLRrrZ3XI1gX7KMk8E3QzPf0zualLDs7cuQmL6l6WiElUAEqumLc7WGpLZZLdSPzNqFSg+CBKCmTI8=
#         # $VIRAL_NGS_METADATA_PATH (for testing metadata logging to s3)
#         - secure: Cd7ch+n8OT0KtA9MhTz1pfXbThJbIQ74oxbSkLGXZKwS52LWwaCH6dtBBbSqXUp9cnxsZhYkxjCmRNgAmBuUh0CpUtgN71YNegYPtLRO1seihqVc3TQC+cgwQxd1hNrsFfAvXwlReLMJgKydGDago0oe5/7df5P+YFAi3w/MKCE=
#       before_install: travis/before_install.sh
#       install:
#         - source travis/install-conda.sh
#         - travis/install-gatk.sh
#         - travis/install-tools.sh
#         - source travis/activate-conda.sh
#       script:
#         - travis/tests-snakemake.sh
#       after_success:
#         - coveralls
#       before_cache:
#         - conda clean --all --yes

######################################
# Old/currently unused travis-ci jobs
######################################

#     #- language: python
#     #  stage: test
#     #  env:
#     #    - TRAVIS_JOB=test_py36_in_docker
#     #    - PYTEST_ADDOPTS="-rsxX -n 2 --durations=25 --fixture-durations=10 --junit-xml=pytest.xml --cov broad_utils --cov illumina --cov assembly --cov interhost --cov intrahost --cov metagenomics --cov ncbi --cov read_utils --cov reports --cov taxon_filter --cov tools --cov util"
#     #    # $BUNDLE_SECRET for decrypting tarball of third-party tools
#     #    - secure: KX7DwKRD85S7NgspxevgbulTtV+jHQIiM6NBus2/Ur/P0RMdpt0EQQ2wDq79qGN70bvvkw901N7EjSYd+GWCAM7StXtaxnLRrrZ3XI1gX7KMk8E3QzPf0zualLDs7cuQmL6l6WiElUAEqumLc7WGpLZZLdSPzNqFSg+CBKCmTI8=
#     #  install:
#     #    - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
#     #    - docker pull $DOCKER_TAG
#     #    - travis/install-gatk.sh
#     #    - pip install coveralls==1.1
#     #    - mkdir coverage
#     #  script:
#     #    - docker run -e _JAVA_OPTIONS -e PYTEST_ADDOPTS -v $GATK_PATH:/gatk -v coverage:/coverage --entrypoint /bin/bash $DOCKER_TAG -c 'set -e; cd /opt/viral-ngs/source; gatk-register /gatk/GenomeAnalysisTK.jar; pytest test/integration test/unit; cp .coverage /coverage'
#     #  after_success:
#     #    - mv coverage/.coverage .
#     #    - coveralls
#     #
#     #- language: generic
#     #  stage: test
#     #  env:
#     #    - TRAVIS_JOB=build_conda_in_docker
#     #    # $ANACONDA_TOKEN for uploading builds to anaconda.org ("broad-viral" channel)
#     #    - secure: SLPB86BpMIiNncMioxVk9cLrqaSNt8F1QDtxkrdLq9j7wXzFqGa7cipG6UJ6Om7GvoF49DpACfGPTA4ycr+T4cH3pWXpBHrBhV8TyKJb23cOmg5+7zqJQTzuwNqKOT7t9rnBkf1uzVXBcgqKaD6XW/nEvNFK00I0cvjlCp8vgxE=
#     #    # $BUNDLE_SECRET for decrypting tarball of third-party tools
#     #    - secure: KX7DwKRD85S7NgspxevgbulTtV+jHQIiM6NBus2/Ur/P0RMdpt0EQQ2wDq79qGN70bvvkw901N7EjSYd+GWCAM7StXtaxnLRrrZ3XI1gX7KMk8E3QzPf0zualLDs7cuQmL6l6WiElUAEqumLc7WGpLZZLdSPzNqFSg+CBKCmTI8=
#     #  install:
#     #    - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
#     #    - docker pull $DOCKER_TAG
#     #    - travis/install-gatk.sh
#     #  script:
#     #    - docker run -v $GATK_PATH:/gatk -e _JAVA_OPTIONS -e TRAVIS_BRANCH -e TRAVIS_PULL_REQUEST -e TRAVIS_TAG -e TRAVIS_COMMIT -e ANACONDA_TOKEN --entrypoint /bin/bash $DOCKER_TAG -c 'set -e; cd /opt/viral-ngs/source; gatk-register /gatk/GenomeAnalysisTK.jar; travis/install-conda-build.sh; travis/build-conda.sh'

# #        - os: osx
# #          language: generic
# #          stage: test
# #          env:
# #              - TRAVIS_JOB=test_osx
# #              - TRAVIS_OSX_PYTHON_VERSION=py36
# #              - TRAVIS_PYTHON_VERSION=3.6
# #          before_install:
# #              - travis/before_install.sh
# #              # Under OSX, some versions of ruby seem to cause this error.
# #              # See: https://github.com/travis-ci/travis-ci/issues/6307
# #              - rvm get head
# #          after_script:
# #              # correct post-build failure on OSX due to non-zero exit code
# #              - set +e
  
