language: python

cache: false

matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          sudo: false
          python: 2.7
        - os: linux
          sudo: false
          python: 3.4
        - os: linux
          sudo: false
          python: 3.5
        # Use generic language for osx
        - os: osx
          language: generic
          env: TRAVIS_OSX_PYTHON_VERSION=py27
        - os: osx
          language: generic
          env: TRAVIS_OSX_PYTHON_VERSION=py35

cache:
 directories:
  - $HOME/virtualenv
  - $HOME/miniconda

env:
  global:
  - CACHE_DIR="$HOME/virtualenv"
  - MINICONDA_DIR="$HOME/miniconda"
  - GATK_PATH="$CACHE_DIR/bin_bundles/GenomeAnalysisTK-3.3-0-g37228af"
  - NOVOALIGN_PATH="$CACHE_DIR/bin_bundles/novocraft_v3"
  - PYTHONIOENCODING=UTF8
  - secure: l9tLtFKGNhaRdRN2N7Fiks63VatVCOtDUG7FI/pi7JNJu/EriTwDRlncoVCRCJZKOdxG8OrwC1BLX6CNqpVjJISEPGV/djsf2wCV9vi6oa+OsvMymsJAjOYkLezwRLVZp/0l/sGumPGz+q+XIM8VnkOZezIvZjGaaAtBpRTHdmA=

# Container pkgs for building diamond.
# These versioned and sources hacks should be removed once travis upgrades to
# Ubuntu 14.04.
addons:
  apt:
    sources:
    - boost-latest # For newer boost
    - ubuntu-toolchain-r-test # For newer gcc
    packages:
    - cmake
    - gcc-4.9
    - g++-4.9
    - libboost1.55-all-dev

before_install:
  - travis/before_install.sh

install:
  - travis/prepare-osx.sh
  - travis/install-conda.sh
  - export PATH="$PATH:$HOME/miniconda/bin"
  - hash -r
  - travis/install-pip.sh
  - travis/install-tools.sh

script:
  - travis/tests-unit.sh
  - travis/tests-long.sh

after_success:
  - coveralls
