language: python
sudo: false

cache:
 directories:
  - $HOME/misc_cache
  - $HOME/virtualenv
  - $HOME/miniconda

env:
  global:
  - CACHE_DIR="$HOME/misc_cache"
  - MINICONDA_DIR="$HOME/miniconda"
  - PIP_DIR="$HOME/virtualenv"
  - GATK_PATH="$CACHE_DIR/bin_bundles/GenomeAnalysisTK-3.3-0-g37228af"
  - NOVOALIGN_PATH="$CACHE_DIR/bin_bundles/novocraft_v3"
  - PYTHONIOENCODING=UTF8
  - secure: l9tLtFKGNhaRdRN2N7Fiks63VatVCOtDUG7FI/pi7JNJu/EriTwDRlncoVCRCJZKOdxG8OrwC1BLX6CNqpVjJISEPGV/djsf2wCV9vi6oa+OsvMymsJAjOYkLezwRLVZp/0l/sGumPGz+q+XIM8VnkOZezIvZjGaaAtBpRTHdmA=

python:
  - 2.7
  - 3.4
  - 3.5

git:
  depth: 3

before_install:
  - travis/before_install.sh

install:
  - travis/install-conda.sh
  - export PATH="$PATH:$HOME/miniconda/bin"
  - hash -r
  - travis/install-pip.sh
  - travis/install-tools.sh

#before_script:
#  - travis/flake8.sh # alternative to landscape.io

script:
  - travis/tests-unit.sh
  - travis/tests-long.sh

after_success:
  - coveralls
