samples: "SampleSheet.csv"
refine_options: 
  novoalign: "-r Random -l 30 -g 40 -x 20 -t 502"
  min_coverage: "3"
seq_center: "ACEGID_RUN"
fastqs_gzipped: false
n_cores: 4
max_ram: 16
ref_genome_dir: "~/resources/ref_genome/genome.fasta"
data_dir: "data"
log_dir: "log"
bin_dir: "~/viral-ngs"
venv_dir: "~/venv"
project: "viral_ngs"
